package com.chansan.extension.itext;

/**
 * @name: Consts
 * @author: leihuangyan
 * @classPath: com.chansan.extension.itext.Consts
 * @date: 2022/12/20
 * @description:
 */
public class Consts {

    public final static String TEST_JSON = """
                            {
                    "name":"小彦",
                    "access":"984038622",
                    "pwd":"6666qAQA",
                    "age":24,
                    "sex":1,
                    "birthday":"1998-05-02",
                    "level":5,
                    "desc":"这是一段描述"
                }
            """;

    public final static String TEST_CONFIG = """
            {
                    "formRef":"elForm",
                    "formModel":"formData",
                    "size":"medium",
                    "labelPosition":"right",
                    "labelWidth":100,
                    "formRules":"rules",
                    "gutter":15,
                    "disabled":false,
                    "span":24,
                    "formBtns":true,
                    "fields":[
                        {
                            "__config__":{
                                "label":"姓名",
                                "labelWidth":null,
                                "showLabel":true,
                                "changeTag":true,
                                "tag":"el-input",
                                "tagIcon":"input",
                                "required":true,
                                "layout":"colFormItem",
                                "span":24,
                                "document":"https://element.eleme.cn/#/zh-CN/component/input",
                                "regList":[
                                    {
                                        "required":true,
                                        "message":"请输入姓名",
                                        "trigger":"blur"
                                    }
                                ],
                                "formId":114,
                                "renderKey":"1141666608532931",
                                "defaultValue":"小彦"
                            },
                            "__slot__":{
                                "prepend":"",
                                "append":""
                            },
                            "placeholder":"请输入姓名",
                            "style":{
                                "width":"100%"
                            },
                            "clearable":true,
                            "prefix-icon":"",
                            "suffix-icon":"",
                            "maxlength":null,
                            "show-word-limit":false,
                            "readonly":false,
                            "disabled":false,
                            "__vModel__":"name"
                        },
                        {
                            "__config__":{
                                "label":"账号",
                                "labelWidth":null,
                                "showLabel":true,
                                "changeTag":true,
                                "tag":"el-input",
                                "tagIcon":"input",
                                "required":true,
                                "layout":"colFormItem",
                                "span":24,
                                "document":"https://element.eleme.cn/#/zh-CN/component/input",
                                "regList":[
                                    {
                                        "required":true,
                                        "message":"请输入账号",
                                        "trigger":"blur"
                                    }
                                ],
                                "formId":113,
                                "renderKey":"1131666608531513",
                                "defaultValue":"984038622"
                            },
                            "__slot__":{
                                "prepend":"",
                                "append":""
                            },
                            "placeholder":"请输入账号",
                            "style":{
                                "width":"100%"
                            },
                            "clearable":true,
                            "prefix-icon":"",
                            "suffix-icon":"",
                            "maxlength":null,
                            "show-word-limit":false,
                            "readonly":false,
                            "disabled":false,
                            "__vModel__":"access"
                        },
                        {
                            "__config__":{
                                "label":"密码",
                                "showLabel":true,
                                "labelWidth":null,
                                "changeTag":true,
                                "tag":"el-input",
                                "tagIcon":"password",
                                "defaultValue":"6666qAQA",
                                "layout":"colFormItem",
                                "span":24,
                                "required":true,
                                "regList":[
                                    {
                                        "required":true,
                                        "message":"请输入密码",
                                        "trigger":"blur"
                                    }
                                ],
                                "document":"https://element.eleme.cn/#/zh-CN/component/input",
                                "formId":105,
                                "renderKey":"1051666606110495"
                            },
                            "__slot__":{
                                "prepend":"",
                                "append":""
                            },
                            "placeholder":"请输入密码",
                            "show-password":true,
                            "style":{
                                "width":"100%"
                            },
                            "clearable":true,
                            "prefix-icon":"",
                            "suffix-icon":"",
                            "maxlength":null,
                            "show-word-limit":false,
                            "readonly":false,
                            "disabled":false,
                            "__vModel__":"pwd"
                        },
                        {
                            "__config__":{
                                "label":"年龄",
                                "showLabel":true,
                                "changeTag":true,
                                "labelWidth":null,
                                "tag":"el-input-number",
                                "tagIcon":"number",
                                "span":24,
                                "layout":"colFormItem",
                                "required":true,
                                "regList":[
                                    {
                                        "required":true,
                                        "message":"年龄",
                                        "trigger":"blur"
                                    }
                                ],
                                "document":"https://element.eleme.cn/#/zh-CN/component/input-number",
                                "formId":101,
                                "renderKey":"1011666605575228",
                                "defaultValue":24
                            },
                            "placeholder":"年龄",
                            "step":1,
                            "step-strictly":false,
                            "controls-position":"",
                            "disabled":false,
                            "__vModel__":"age"
                        },
                        {
                            "__config__":{
                                "label":"性别",
                                "labelWidth":null,
                                "showLabel":true,
                                "tag":"el-radio-group",
                                "tagIcon":"radio",
                                "changeTag":true,
                                "defaultValue":1,
                                "layout":"colFormItem",
                                "span":24,
                                "optionType":"default",
                                "regList":[
                                    {
                                        "required":true,
                                        "message":"性别不能为空",
                                        "trigger":"change"
                                    }
                                ],
                                "required":true,
                                "border":false,
                                "document":"https://element.eleme.cn/#/zh-CN/component/radio",
                                "formId":106,
                                "renderKey":"1061666606167927"
                            },
                            "__slot__":{
                                "options":[
                                    {
                                        "label":"男",
                                        "value":1
                                    },
                                    {
                                        "label":"女",
                                        "value":2
                                    }
                                ]
                            },
                            "style":{
                                
                            },
                            "size":"medium",
                            "disabled":false,
                            "__vModel__":"sex"
                        },
                        {
                            "__config__":{
                                "label":"生日",
                                "tag":"el-date-picker",
                                "tagIcon":"date",
                                "defaultValue":"1998-05-02",
                                "showLabel":true,
                                "labelWidth":null,
                                "span":24,
                                "layout":"colFormItem",
                                "required":true,
                                "regList":[
                                    {
                                        "required":true,
                                        "message":"请选择生日",
                                        "trigger":"change"
                                    }
                                ],
                                "changeTag":true,
                                "document":"https://element.eleme.cn/#/zh-CN/component/date-picker",
                                "formId":115,
                                "renderKey":"1151666608656321"
                            },
                            "placeholder":"请选择生日",
                            "type":"date",
                            "style":{
                                "width":"100%"
                            },
                            "disabled":false,
                            "clearable":true,
                            "format":"yyyy-MM-dd",
                            "value-format":"yyyy-MM-dd",
                            "readonly":false,
                            "__vModel__":"birthday"
                        },
                        {
                            "__config__":{
                                "label":"级别",
                                "tag":"el-rate",
                                "tagIcon":"rate",
                                "defaultValue":5,
                                "span":24,
                                "showLabel":true,
                                "labelWidth":null,
                                "layout":"colFormItem",
                                "required":true,
                                "regList":[
                                    {
                                        "required":true,
                                        "message":"级别不能为空",
                                        "trigger":"change"
                                    }
                                ],
                                "changeTag":true,
                                "document":"https://element.eleme.cn/#/zh-CN/component/rate",
                                "formId":116,
                                "renderKey":"1161666608673555"
                            },
                            "style":{
                                
                            },
                            "max":5,
                            "allow-half":false,
                            "show-text":false,
                            "show-score":false,
                            "disabled":false,
                            "__vModel__":"level"
                        },
                        {
                            "__config__":{
                                "label":"描述",
                                "labelWidth":null,
                                "showLabel":true,
                                "tag":"el-input",
                                "tagIcon":"textarea",
                                "defaultValue":"千万不要崩啊",
                                "required":true,
                                "layout":"colFormItem",
                                "span":24,
                                "regList":[
                                    {
                                        "required":true,
                                        "message":"请输入描述",
                                        "trigger":"blur"
                                    }
                                ],
                                "changeTag":true,
                                "document":"https://element.eleme.cn/#/zh-CN/component/input",
                                "formId":104,
                                "renderKey":"1041666606108118"
                            },
                            "type":"textarea",
                            "placeholder":"请输入描述",
                            "autosize":{
                                "minRows":10,
                                "maxRows":4
                            },
                            "style":{
                                "width":"100%"
                            },
                            "maxlength":null,
                            "show-word-limit":false,
                            "readonly":false,
                            "disabled":false,
                            "__vModel__":"desc"
                        }
                    ]
                }
            """;

}
